### PR TITLE
Add travis and coveralls config file

### PR DESCRIPTION
**Pull request by uvchik**
Try to add CI services according to #21.

[Coverage Status](https://coveralls.io/github/wind-python/windpowerlib?branch=features%2Fadd_ci) [Build Status](https://travis-ci.org/wind-python/windpowerlib)

### CODE REVIEW

**Comment by uvchik** [comment]
Okay, basically it seems to work (see badges in the first comment).

1. I removed the test of the jupyter notebook to make the tests pass but I will reactivate it to make the test fail again. @birgits Could you repair or finally remove the test.
2. I had to deactivate the doctest of the [linear_interpolation_extrapolation](https://github.com/wind-python/windpowerlib/pull/22/files#diff-bf50890b1d23dde97dd903475b288cf0) function, because python 3.6 on travis ignored the `round` command. I have no idea why. As there are already unit tests, that test this function it is no problem to deactivate this doctest.
3. In oemof we use only the pr-tests and not the push-tests. By default both test has been activated. @wind-python/team What do you think?

**Comment by uvchik** [comment]
Damned, I did not want to spend time on this but I solved the jupyter issue. It fails for python < 3.6. That does not mean that the notebook itself fails on python 3.5 but the conversion for test fails. I think it is not worth fixing this. We should try to keep the `example.py` and the `example.ipynb` in line so that the code itself is tested for all python versions.

**Comment by uvchik** [comment]
> In oemof we use only the pr-tests and not the push-tests. By default both test has been activated. @wind-python/team What do you think?

This is the last open question but we do not have to decide it now. I think it is good to merge this soon, to test it for a while.

**Comment by SabineHaas** [comment]
> > In oemof we use only the pr-tests and not the push-tests. By default both test has been activated. @wind-python/team What do you think?
> 
> This is the last open question but we do not have to decide it now. I think it is good to merge this soon, to test it for a while.

I think it is enough for us to use the pr-tests as usually all branches are based on the master branch which means that there won't be a difference between pr- and push-tests as far as I understood from reading online.

**Pull request merged**
