### PR TITLE
Revise py-script examples and copy to oemof-examples

### LINKED ISSUE #88: Revise py-script examples and copy to oemof-examples
- [x] clean example
- [x] download weather data automatically
- [x] include weather data conversion and read_csv with multiindex files
- [x] copy examples to oemof-examples

### PR DESCRIPTION
**Pull request by uvchik**
Fixes #88

### CODE REVIEW

**Comment by birgits** [comment]
Thanks for this PR @uvchik. I like that the weather data is automatically downloaded now! If I understood it correctly though, the dummy csv files containing power and power coefficient curves still need to be downloaded manually, right? I think it's fine for now as it is my task to get rid of them altogether (see #73). But I would wait with moving the examples to the oemof examples repository until I did this. Besides that I don't have any other comments.

**Comment by uvchik** [comment]
I removed the dummy turbine in the example at [oemof-examples](https://github.com/oemof/oemof-examples/blob/master/oemof_examples/windpowerlib/v0.2.x/modelchain_example.py), so in that example only the weather data is needed.

I could the remove the dummy turbine in the internal example as well but I was not sure whether  or not people might be interested in this use case.

**Comment by birgits** [comment]
Mmh, I'm undecided... It might be useful to show people how they can provide their own turbine library file. So I guess I'm leaning more towards leaving the dummy turbine file.

**Comment by SabineHaas** [comment]
Oh the other hand, the [oedb file](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/oedb/power_curves.csv) already shows the structure such a file must have. 
What about adding a line in the example saying something like 

_"You can load your own power (coefficient) curve data from a file structured like link_to_oedb_files"._

I'd be fine with both removing and keeping the files.

**Comment by uvchik** [comment]
I tend to remove the dummy turbine.

If people convert their data to the windpowerlib format they should send it to us, so that we can add it to the oedb and the windpowerlib. In that case the data will be available for everyone.

If people have their data in a different format they can use the way we show with the `my_turbine` example.

**Comment by uvchik** [comment]
I added another variant to create a `my_turbine`. I think it is much better to show users how to add their own data in the windpowerlib structure than to make them creating special csv-files.

So, I would remove the dummy data and improve the examples on how to use your own data. Have a look at the new example script to see what I mean. I could remove all csv files but the notebooks would not work anymore.

**Comment by uvchik** [comment]
I added information about how to integrate your own data to getting started/README.

I think this is enough and easier to handle constructing a special csv-file as suggested in the dummy_turbine example. Therefore, I vote for removing it from the examples.

https://github.com/wind-python/windpowerlib/tree/features/revise-python-script-examples#wind-turbine-data

**Comment by uvchik** [comment]
Any comments? 

If you like the idea we could remove the "dummy_turbine" from the notebooks as well and remove the csv-files.

There are some typos in the README. We should fix them in case we do agree in the basic idea.

**Comment by Ludee** [comment]
I'm not sure if I understand it right, but from the data management perspective, I would recommend to keep the data template files.

**Comment by uvchik** [comment]
In my opinion these files are not meant as templates but as example files. Otherwise I would not hide them in  `windpowerlib/example/data/power_coefficient_curves.csv`.

I do not see the sense of template files there, except in the context of "How to send your own turbine data to the oedb". But this should be placed elsewhere not in the examples.

**Comment by uvchik** [comment]
Okay, it seems that there are no objections.

@birgits Will you integrate the changes in the Notebooks?

**Pull request merged**
