### PR TITLE
Features/add wind farm init option

### PR DESCRIPTION
**Pull request by birgits**
Changes proposed in this pull request:
- Enable WindFarm initialization with total installed capacity per wind turbine type. 
Right now it is only possible to define a wind farm by giving the number of turbines installed per type. For calculations in the feedinlib it is useful to also enable an instantiation using the installed capacity per type.

@SabineHaas if this looks good to you I will adapt the examples to include this new possibility to define a wind farm.

### CODE REVIEW

**Comment by uvchik** [comment]
This PR was the impulse to look into the `WindFarm` class. 

1.  What happens if the number of turbines is not an integer? Is it possible? I could not find anything about it. If it is not allowed, we should check it, especially if we allow to calculate it from the `nominal_power` and the `total_capacity`.

2. Why should people want to pass the total capacity? They should know the `nominal_power` anyway because they need to be sure that  the `total_capacity` is a multiple of the `nominal_power`. If they are able to check if the `total_capacity` is a multiple of the `nominal_power`, they will be able to calculate the number of turbines and pass it to the class.

3. In the long run it would be nice to have `WindTurbineGroup` class which is basically a `WindTurbine` but with a number of turbines of the same type. If we do have such a class it is (in my opinion) much clearer to define a `WindFarm` object. We could inherit from the `WindTurbine` class and just add the number of turbines. All tests regarding such a group would be in this class and not in the `WindFarm` class. We would have well defined attributes of a class instead of keys of a dict, which would be easier to understand in the API docs. It is not urgent but we could think of adding this to the v0.2 release if you like the idea.

**Comment by birgits** [comment]
@uvchik 
1. It is possible to have float values as number of turbines.
2. It is useful when calculating the feedin for a region. In that case one usually has some kind of turbine register or installed capacity for a region with usually unknown turbine types and might want to use representative turbines where each has some share of the total capacity. Now one could either calculate the feedin for each turbine type separately and then scale it according to the share in installed capacity or use the WindFarm that calculates the feedin for several turbine types in one calculation step, which is what we want to do and why this new functionality is useful to us. In the feedinlib the wind turbine or wind farm classes for each model are not initialized until the feedin is actually calculated which is why the nominal capacity of some wind turbine type is not known in the program when setting up the WindFarm.
3. I think an additional class might be too much and more confusing for such a small change. @SabineHaas what do you think?

**Comment by SabineHaas** [comment]
3. As we already have WindTurbineCluster it could indeed be confusing to have even one more class. @uvchik do you think your idea could be implemented into this class?

**Comment by birgits** [comment]
@SabineHaas I think that might be even more confusing as you would then have to setup a WindFarm using WindTurbineCluster's and the WindTurbineCluster that consists of several wind farms using the WindFarm class...

**Comment by uvchik** [comment]
1 + 2) Okay. It does make sense if non-integer number of turbines is allowed.

3) I still think such a group would be a good idea. We do have this group anyway. Now it is a dict and I think it is clear if it is class. For me it is a question of documentation.

@birgits @SabineHaas Is this right?

windpowerlib

**Comment by uvchik** [comment]
We could add the number of turbines and the total capacity to the WindTurbine class but I think it is cleaner to define a new class.

**Comment by SabineHaas** [comment]
3. While discussing with @birgits I learned that I misunderstood the purpose of the class you suggested, @uvchik. I think this should neither be included into `WindTurbineCluster` nor into `WindTurbine`. However, an additional class might indeed be confusing and even complicated: You would need to initialize `WindTurbine`s, then `WindTurbineGroup`s to finally arrive at the `WindFarm` object.   

@uvchik: Is it the dictionary that makes a `WindFarm` not clearly defined for you? It should be possible to use both pd.DataFrame and dict and we could show data frames in the example instead of dictionaries for a better overview.

**Comment by uvchik** [comment]
I do not understand why an extra class is more complicated for you.

At the moment the initialisation of a wind farm looks like this:

```python
enerconE126 = {
   'hub_height': 135,
   'rotor_diameter': 127,
   'turbine_type': 'E-126/4200'}
e126 = wind_turbine.WindTurbine(**enerconE126)
dummy2 = {
   'hub_height': 125,
   'rotor_diameter': 100,
   'turbine_type': 'Dummy2}
d02 = wind_turbine.WindTurbine(**dummy2)
example_farm_data = {
    'name': 'example_farm',
    'wind_turbine_fleet': [{'wind_turbine': e126,
                            'number_of_turbines': 6},
                            {'wind_turbine':d02,
                            'number_of_turbines': 8}]}
example_farm = wind_farm.WindFarm(**example_farm_data)
```

With a WindTurbineGroup it would look like this:

```python
enerconE126 = {
   'hub_height': 135,
   'rotor_diameter': 127,
   'turbine_type': 'E-126/4200'}
g6_e126 = wind_turbine.WindTurbineGroup(number_of_turbines=6, **enerconE126)
dummy2_group = {
   'hub_height': 125,
   'rotor_diameter': 100,
   'turbine_type': 'Dummy2,
   'number_of_turbines': 8}
g8_d02 = wind_turbine.WindTurbineGroup(**dummy2)
example_farm = wind_farm.WindFarm('example_farm', [g6_e126, g8_d02])
```

This would work with 'total_capacity' as well.

In my opinion it should also be possible to define a WindTurbineGroup with a WindTurbine object, if you already have one.

```python
enerconE126 = {
   'hub_height': 135,
   'rotor_diameter': 127,
   'turbine_type': 'E-126/4200'}
e126 = wind_turbine.WindTurbine(**enerconE126)
g6_e126 = wind_turbine.WindTurbineGroup(number_of_turbines=6, e126)
```

One important thing for me is, that you will have a clean docstring.
```rst
class WindTurbineGroup(WindTurbine):
[...]
number_of_turbines : float
    The number of turbines of the same type...
total_capacity : float
    The overall capacity....
[...]
```

For me it seems to be a cleaner design like this but if you are not convinced you can just go on. I will be quiet from now on...

**Comment by birgits** [comment]
Rather than introducing a new class I propose allowing to provide the wind turbine fleet as a DataFrame (see proposed changes in this PR). This will not break the current API, still allowing users to provide their turbine fleet as a list, but at the same time allow a clearer and easier to provide data structure. 
In my opinion having to cope with another class will not make the usage of the wind farm easier. I also only see two ways right now how this new WindTurbineGroup class could look like. One is that it is just a simple data container holding the turbine type and number of turbines of that type, in which case I don't see the advantage towards a DataFrame. The other one is that it is a class very similar to WindFarm just with only one turbine type and different parameters which would mean that we'd have to maintain another class that doesn't provide additional functionality.

**Comment by birgits** [comment]
@uvchik we decided to move the discussion about a new class to a new [issue](#65) as it goes beyond the intended changes of this PR.
@SabineHaas and I also talked about my proposed changes to allow providing the wind turbine fleet as a dataframe and decided not to revert the changes as it doesn't break with the current API, is in our opinion easier to use and will also not impede possible future changes that could be an outcome of the discussion in issue #65.

**Pull request merged**
