### PR TITLE
Vectorize _get_power_output calculations

### PR DESCRIPTION
**Pull request by kyri-petrou**
This PR reduces the time computation required for the power_curve_density_correction function by vectorizing the calculations in the `_get_power_output` function.

On a dataset with around ~200k datapoints, the computation time was reduced from ~6seconds to ~2seconds. This might help speed up computation even more when larger datasets are used.

Changes proposed in this pull request:
- Use of vectorized numpy functions along with `map()` to speed up the `power_curve_density_correction` function

### CODE REVIEW

**Comment by kyri-petrou** [comment]
What would be the best way to resolve the failing test? We could either:
- change the test to expect the new error that is thrown
- assert array sizes and dtypes for all arrays at the start of the function and raise an appropriate error (and change the tests accordingly)

**Comment by uvchik** [comment]
Thank, you @kyri-petrou for your contribution. I somehow missed the notification, so I just saw your changes.

If I wrote this test I cannot remember why :see_no_evil: .

We test for wrong input types but the function does not check the input type, therefore the test does not make sense. So I would just remove it.

If you like, you can test the input type and write an appropriate test.

The problem is that all list-like objects are allowed. But a string is also iterable and a string is not allowed.

I found this ([source](https://stackoverflow.com/questions/19943654/type-checking-an-iterable-type-that-is-not-a-string/19944281)):

```python
if isinstance(obj, str) or not hasattr(obj, '__iter__') 
    raise TypeError ...
```

**Comment by uvchik** [comment]
I will merge this and remove the failing test afterwards. I think it is good to have this PR in the upcoming release.

Thank you @kyri-petrou.

**Comment by kyri-petrou** [comment]
Apologies, for some reason I must have not seen the notification for your comment above! Glad that to hear though that it's been merged! Much appreciated

**Pull request merged**
