### PR TITLE
Add stickler and black config files

### LINKED ISSUE #81: Shall we use structure and pep checker
In other oemof packages various structure and pep checkers are used. Shall we also integrate some of them. We can ask other contributors on the developer meeting and decide after/on the meeting.

This is a reminder, for the windpowerlib session at the oemof developer meeting in December (https://oemof.org/news/).

### PR DESCRIPTION
**Pull request by uvchik**
Fixes #81 .

Test stickler-ci for the windpowerlib.

### CODE REVIEW

**Comment by vezeli** [comment]
@uvchik If this gets merged and the contributors are supposed to run Black before submitting a PR than adding information in "Contributing" reflecting this should be needed? Also adding it now seems OK.

**Comment by uvchik** [comment]
If it works as intended you do not have to run Black before submitting a PR. At the moment you have to follow the pep rules anyway. Stickler-ci will check that and Black may fix it automatically but at the moment it does not seem to work. Maybe I have to merge it to get it work.

**Comment by vezeli** [comment]
Oh nice, that is actually a really neat service to have! When you get it working I found some information [here](https://github.com/peterjc/flake8-black#configuration) and [here](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) that accounts for the incompatibility between flake8 and black and makes them work together better.

**Comment by uvchik** [comment]
Now it works. According to @gnn the black style might not be "everybody's darling" but is well documented and every decision is explained in the black documentation. I personally do not like everything but as it makes things easier so I would vote for using it.

**Comment by SabineHaas** [comment]
Thanks for implementing this @uvchik! 
I have to admit that I don't like the open brackets being moved to the next line.. Is there any way to change settings?

Anyways, I really appreciate that we then have a consistent style (no matter the brackets ;)) 
:)

**Comment by uvchik** [comment]
> I have to admit that I don't like the open brackets being moved to the next line.. Is there any way to change settings?

I do not like them either :smirk: 

But I would not change it, because of two reasons.

1. If you start with exceptions you could discuss any style element. Why not use 100 instead of 80 characters and so on. To avoid such discussions I would use the full package without exceptions (de gustibus non est disputandum).

2. Black really explains everything. In this case it is used to make diff-files easier to read (->https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines)

I would like both of you (@birgits, @SabineHaas) to approve this issue. @vezeli already reacted with the :+1: emoji.

**Pull request merged**
